# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-18 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_passwd', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
            ],
        ),
    ]
