# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2019-03-06 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=20)),
                ('user_passwd', models.CharField(max_length=20)),
                ('user_email', models.CharField(max_length=20)),
            ],
        ),
    ]
